apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: "mailhog:1025"
      smtp_from: "ids-alert@k8s-ids.local"
      smtp_require_tls: false
    route:
      receiver: "email-soc"
      group_by: ["alertname"]
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 30m
    receivers:
      - name: "email-soc"
        email_configs:
          - to: "soc@k8s-ids.local"
            send_resolved: true
            headers:
              Subject: ' IDS Kubernetes: {{ .CommonAnnotations.summary }}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels: { app: alertmanager }
spec:
  replicas: 1
  selector:
    matchLabels: { app: alertmanager }
  template:
    metadata:
      labels: { app: alertmanager }
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - { containerPort: 9093 }
          volumeMounts:
            - { name: config, mountPath: /etc/alertmanager }
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 300m, memory: 256Mi }
      volumes:
        - name: config
          configMap: { name: alertmanager-config }
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels: { app: alertmanager }
spec:
  selector: { app: alertmanager }
  ports:
    - { port: 9093, targetPort: 9093 }
